# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/tegra3-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/tegra3-common/proprietary/etc/firmware/mXT1386_08_AA.bin:system/etc/firmware/mXT1386_08_AA.bin \
    vendor/motorola/tegra3-common/proprietary/etc/firmware/mXT1386_08_E1.bin:system/etc/firmware/mXT1386_08_E1.bin \
    vendor/motorola/tegra3-common/proprietary/etc/firmware/mXT1386_09_AA.bin:system/etc/firmware/mXT1386_09_AA.bin \
    vendor/motorola/tegra3-common/proprietary/etc/firmware/mXT1386_10_AA.bin:system/etc/firmware/mXT1386_10_AA.bin \
    vendor/motorola/tegra3-common/proprietary/etc/firmware/mXT1386_10_FF.bin:system/etc/firmware/mXT1386_10_FF.bin \
    vendor/motorola/tegra3-common/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so
